### ISSUE TITLE
Whatsapp bot for CARE

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#10530]
## Project Detail

CARE is a centralized capacity management and patient management system, central to the 10BedICU Project, integrating patients, doctors, hospitals, labs, specialized treatment centers, hospital administrators, and shifting control cells. Hospitals update crucial information about their assets, providing district administration with a comprehensive view of the healthcare system via smart dashboards. CARE digitizes patient records, streamlines workflows for pandemic management, and is deployed in remote areas, enabling Tele-ICU services for underserved citizens. It revolutionizes healthcare management, enhancing efficiency, accessibility, and patient outcomes.

## Features To Be Implemented

Build a wrapper on care that IM bots can use to get information or send a notification. The idea behind this feature is to ease and improve the user experience. 

- [ ] Build a generic IM wrapper for care which the respective bots can use to interact with care
- [ ] Build a WhatsApp bot which can be used by both patients and hospital staff
  
  For Patients
  - [ ] Should fetch their patient records
  - [ ] Should fetch their current medications
  - [ ] Should fetch their procedures
  
  For Users (Hospital Staff)
  - [ ] Should fetch their schedules (to be done after scheduling)
  - [ ] Option to fetch asset status
  - [ ] Option to fetch inventory data
 
_The above-mentioned list of items (both For Patients and For Users) is subject to change, the mentioned features are just to give an idea of what needs to be done._

_While implementing this, a conscious effort should be taken to prevent the Private Personal Information (PPI) of other patients from being shared._

## Learning Path

|  | Details |
| :---:  | :---:  |
| Complexity       | Medium |
| Required Skills | Python, Django |
| Mentors            | @vigneshhari , @khavinshankar , @rithviknishad , @gigincg , @Ashesh3 , @sainak |
| Project Size      | 175 Hours |

## Link to documentation for Product Set-Up

1. For setting up the frontend, please refer to the readme file available at: https://github.com/coronasafe/care_fe
2. For setting up the backend, please refer to the readme file available at: https://github.com/coronasafe/care

## Acceptance Criteria

- Code is logically structured for long-term project sustainability.
- Proper descriptions should be included for review purposes.
- QA and Code Review

## Milestone

- [ ] Get to know CARE as a product and understand the workflow.
- [ ] Understand the requirements.
- [ ] Implement the tasks mentioned above
- [ ] Write tests for the implemented functionality
- [ ] Optimise the code
- [ ] Review and QA

**Comment by nihal467** [comment]
Hey everyone,

Thank you for showing interest in the projects. I would like to inform you that we have scheduled **EOD calls on Zoom** from Monday to Saturday at **7:30 PM** to discuss your work and address any doubts with the core team. Alternatively, feel free to use our **#care_general** Slack channel.

The meeting links will be shared in our **#reminder** channel in our Slack workspace. 

**Link to join the Slack:** [Slack Workspace](https://join.slack.com/t/rebuildearth/shared_invite/zt-2blycdt83-yvoJRsa10QDhE9WFiwoVkg)

Meanwhile, please explore the care platform and familiarize yourself with its features. Feel free to play around with it and assign any open issues as you see fit.

**Comment by NutNick31** [comment]
Hello @nihal467 ,

I am Rajesh Kumar Singh an undergraduate engineering student, with strong passion in full-stack development. I have read the problem statement and I am really interested to contribute to this project.

I have read the project features to be implemented and I think my skills be really helpful for the project, as it's requirements align with my past experience, I have worked with developing chat bots before, I have developed a chat bot my self in a hackathon hosted my Morgan Stanley, I built it in a react native application. Additionally I have built telegram bots using Aiogram in python. I think my skills will be really helpful for the project.

**Overview**:
The project involves building a wrapper for the CARE platform to facilitate interaction via instant messaging (IM) bots, with a focus on improving user experience. Additionally, a WhatsApp bot will be developed to serve both patients and hospital staff, providing functionalities such as fetching patient records, medications, procedures, schedules, asset status, and inventory data.

Roadmap:
1) Wrapper Development: Create IM wrapper API for CARE platform.
2) WhatsApp Bot Development: Build bot for patient and staff interaction with help of **TWILIO**.
3) Privacy Measures: Implement data protection measures.
4) Testing and Deployment: Test, deploy, and monitor.

**Comment by Sakshamgupta90** [comment]
Hi @nihal467,
I am Saksham Gupta, a final year student from Delhi, India. I interested in this project.
I am proficient in both django and python and currently working in healthcare startup as well.

**Comment by sravyakaranam** [comment]
Hi @nihal467, @vigneshhari , @khavinshankar, @rithviknishad, @gigincg, @Ashesh3, @sainak,
I am Sravya Karanam, currently Computer Science Graduate Student at North Carolina State University, Raleigh, USA.
I'm excited to take on this project and contribute to the development of CARE. I have experience with Django and Python, having successfully implemented two projects using these technologies. I'm eager to dive into the requirements, understand the workflow, and implement the necessary features mentioned in the issue.

Looking forward to your guidance throughout the process.

**Comment by gigincg** [comment]
@sravyakaranam 

Looking forward to your contributions. Feel free to ask if you have any questions, we've tried to detail out the project well in this issue, happy to make any further clarifications

Do Join our Slack Channel for any discussions and to work closely with the core team

**Comment by gigincg** [comment]
> Hi @nihal467,
> 
> I am Saksham Gupta, a final year student from Delhi, India. I interested in this project.
> 
> I am proficient in both django and python and currently working in healthcare startup as well.
> 
> 

Hey @Sakshamgupta90 

Feel free to join our calls for any questions and make a proposal for the GSoC Project

**Comment by gigincg** [comment]
> Hello @nihal467 ,
> 
> 
> 
> I am Rajesh Kumar Singh an undergraduate engineering student, with strong passion in full-stack development. I have read the problem statement and I am really interested to contribute to this project.
> 
> 
> 
> I have read the project features to be implemented and I think my skills be really helpful for the project, as it's requirements align with my past experience, I have worked with developing chat bots before, I have developed a chat bot my self in a hackathon hosted my Morgan Stanley, I built it in a react native application. Additionally I have built telegram bots using Aiogram in python. I think my skills will be really helpful for the project.
> 
> 
> 
> **Overview**:
> 
> The project involves building a wrapper for the CARE platform to facilitate interaction via instant messaging (IM) bots, with a focus on improving user experience. Additionally, a WhatsApp bot will be developed to serve both patients and hospital staff, providing functionalities such as fetching patient records, medications, procedures, schedules, asset status, and inventory data.
> 
> 
> 
> Roadmap:
> 
> 1) Wrapper Development: Create IM wrapper API for CARE platform.
> 
> 2) WhatsApp Bot Development: Build bot for patient and staff interaction with help of **TWILIO**.
> 
> 3) Privacy Measures: Implement data protection measures.
> 
> 4) Testing and Deployment: Test, deploy, and monitor.

@NutNick31 Your Roadmap looks good as a very minimal overview. Please do make a detailed proposal to take up the project as part of GSoC.

Please note that we would prefer not to use Twilio but WhatsApp's official APIs. Also, ensure that your approach is modular enough such that the WhatsApp part is switchable with any other IM in the future

**Comment by raphaelgogo** [comment]
Hi, am Raphael Gogo from the University of Cape Coast, Ghana. I read about the Problem and I am interested in this Project.

**Comment by jasonxiexy** [comment]
Hello,
My name is Xiaoyang (Jason) Xie, and I am a Master student currently at University of Toronto studying computer engineering, and undergraduate studies in computer science at Western Univeristy. I am excited about the opportunity to contribute to the Whatsapp bot for CARE for Open HealthCare Network.

Having focused my studies on algorithms, full-stack development and other software engineering skills, I am particularly interested in contributing to projects that involve the implementation of healthcare technology and its potential to transform patient care. I believe my background and skills align well with several aspects of this topic, including:

1. Proficiency in Java and Python for backend development, automation, and data processing tasks.
2. Experience with frameworks like flask, Spring Boot, Hibernate, and Robot Framework for building robust backend services, database operations, and automated testing.
3. Familiarity with Docker, Jenkins, and Agile methodologies for efficient deployment, continuous integration, and responsive project management.

I am committed to delivering a functional and user-centric GUI for the robust data handling capabilities, and interactive visualization tools. I look forward to collaborating with the team to achieve our goals and make impactful contributions to the project.

Thank you for considering my candidacy, and I am eager to contribute my skills and expertise to this exciting endeavor.
Jason Xie
xjason0312@gmail.com
https://www.linkedin.com/in/jasonxie0312/

**Comment by jhemeel** [comment]
Good day,
I am **Jemeel Sadique** from Nigeria. I am a graduate of _Human Medicine,_ also a _Full Stack Python Developer_ with a strong background in software development and a passion for creating innovative solutions. My experience includes developing web applications, data analysis tools, and automation scripts using Python and related technologies.

I possess a solid foundation in Python programming, along with expertise in popular frameworks such as Django. I am eager to leverage my skills and knowledge to contribute to your projects and help drive your organization's success. I am confident in my ability to deliver high-quality code and solutions that meet your requirements and exceed expectations.

After reading through the features that need to be implemented, I believe that my skills will be very beneficial for the project because the requirements match my previous experience working with chat bot development. I have even created a chat bot myself  using Django channels and chatterbox. Furthermore, I have developed a full stack **_Online  Booking and Medical Consultation_** web application using Django.

Thank you for considering my application. I am excited about the prospect of working together and contributing to your projects.

**Comment by nihal467** [comment]
closing this in favour of the new issue : https://github.com/ohcnetwork/care_fe/issues/10599
