### ISSUE TITLE
Edits to ICU Module

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#1973]
Some fields in ICU module were misplaced. 

The correct placement of these fields are marked in Column R of the master sheet at https://docs.google.com/spreadsheets/d/12l6pyxopoZjrD4KFEksh2D1h0qQnbgb9e0oAMNxQdW8/edit?usp=sharing

### Task
- [x]  Remove fields from consultation form
- [x] Make Operation & Special Instructions non-mandatory (Care backend)
- [ ]  Add fields in Icu module
