### ISSUE TITLE
TeleICU Hub View UI

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2109]
Create the Following UIs for TeleICU Hubs to manage spokes 

- [x] New Camera Feed Screen #2107 
- [x] List Spokes facilities #2094 
- [x] Collapsible Sidebar #2101 
- [x] List of Patients in a Spoke #2106
- [x] Patient Detail Screen #2108
