### ISSUE TITLE
Usability bugs

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2200]
- [ ] Marking is missing in graph : Consultation page #2199 
- [ ] Adjust Investigation detail page in Consultation #2198 
- [ ] Unable to edit existing investigation data #2197 
- [ ] File upload function in consultation page is malfunctioning #2196 
- [ ] Data's are Overlapping in Consultation page #2195 
- [ ] Landing page malfunction in consultation page #2193 
- [ ] Existing Consultation Log Update is malfunctioning #2194 
- [ ] Something went wrong pop-up in TeleICU #2191
