### ISSUE TITLE
Revamping Patient registration:

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2218]
Patient registration process needs to be revamped.

**Part 1: Changes to be made in the patient registration form** (https://care.coronasafe.in/facility/6e401539-e27f-4aff-a626-c9d42427ffd7/patient) @sam9111 
- [x] - Remove "Frontline Worker"
- [x] - Remove "Is a medical worker?"
- [x] - Remove "Is a Guests Worker?"
- [x] - Remove "Domestic International Air Travel"
- [x] - Add short text field for "Occupation"

Only personal details of the patient need to be captured in the registration form. The health and medical history details will be moved to the consultation form. Details in Part 2 below.
______________________________

**Part 2 : Changes to be made in the consultation form** (https://care.coronasafe.in/facility/05980e8f-8860-4460-b863-fefdff1d187b/patient/e45b93eb-4b1a-4f91-9b6f-3533b719e9a6/consultation) @sam9111 

HEALTH DETAILS

- [ ] - Add a new collapsable section to the consultation form on top. This section will contain all health details of the Patient.
- [ ] - The first field is "Allergy"- YES/NO. If YES, a short text box for details. (the text field already exists in the patient registration form. the same may be migrated)
- [ ] - Second field will be for "Vaccinations". The user must be able to select multe inputs from the options. The Options would be: COVID (1 dose, 2 dose), Hep B, Hep A. (The field for COVID Vaccinationa already exists in patient registration form)
- [ ] - "Blood Group" With dropdown. (The field already exists in the patient registration form and may be migrated here)
- [ ] - Field for "Weight" and "Height" existing at the bottom of the consultation form may be moved up to the top after blood group.
- [ ] - Add a Long Text Field for "Familty Details"
- [ ] Remove all other fields from the section

--------------------

MEDICAL HISTORY

- [ ] - Add a second collapsable section after health details for the medical history of the patient
- [ ] - Add Field for "Present Health Condition" and "Ongoing Medication" (Field already exists in patient registration form. Migrate the same here.)
- [ ] - Add Field for **Medical History**. Details of this section are as below
1. A field on the left will capture Date as DD/MM/YYYY. The user needs to have the option of choosing on Month and year (MM/YYYY) or only the Year (YYYY). 
2. Once the date is selected in the middle, a text field to search through all diseases must appear. This text field must allow the user to type and search through any disease in ICD-11 (Internal Classification of diseases available at https://icd.who.int/en). The user must be able to find the right disease and select it. We need to also have an "Others" option here for when the user is not sure about the ICD category.
3. Once the disease is selected, a long text description box must also appear. 
4. An option to add more sections of date, ICD and description must always appear below. This will allow users to keep adding more and more details about their medical history across various dates.
5. For every saved date, ICD and description, there needs to be an option on the right-hand side to "mark as cured". This will allow the system to not only list all the diseases the patient has but also understand which of it is already cured. 

The above 2 sections will appear expanded only in the 1st Consultation on any patient card. In the subsequent consultations, These sections will be autofilled and minimised to show only the title. The user may expand it and make edits. 

- [ ] remove all other fields from the section

-----------------
CONSULTATION DETAILS
- This section will have the present consultation form. This section will NOT be autofilled unlike the above sections.

**Comment by aparnacoronasafe** [comment]
Adding occupation field: https://github.com/coronasafe/care_fe/issues/2588

**Comment by aparnacoronasafe** [comment]
@developedBySJ Can you follow through on this issue? Could you see if you can break it further to smaller issues and let multiple people work on it? 

We need to close this issue asap

**Comment by nihal467** [comment]
@aparnacoronasafe can you reverify the issues and close it / modify it

**Comment by nihal467** [comment]
As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by bodhish** [comment]
@aparnacoronasafe @nihal467 looks like everything is checked in the issue, can we close this?

**Comment by aparnacoronasafe** [comment]
@bodhish revised the checklist. A lot of things remains.

This issue is broken up and filed as separate issues with a lot more details. All the issues are marked as Blocked and to be taken up after events module is done. 

Since events module is deployed, is this a good time to complete all the issues? @gigincg

**Comment by bodhish** [comment]
I am not sure if it should be a single form; This approach is great for 1st time registrations in all other possible cases we just need to add each of those details one or few at a time.

**Comment by gigincg** [comment]
Closing in Favour of #8388
