### ISSUE TITLE
Medical History: Introduce timeline format

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3361]
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

In the Medical History section, Retain the "Present Health Condition" and "Ongoing Medication field" as it is.  The Blood group and Allergies field are moved to the health details through #3332 and #3335. 

There is a field "Any medical history? " with multiple choice options. 

Replace this with the following. 

DATA INPUT

- [ ] Section heading: Medical History (this will be a sub-section within the larger medical history collapsable section itself) refer to the design below

- [ ] A field on the left will capture Date as DD/MM/YYYY. The user needs to have the option of choosing only Month and year (MM/YYYY) or only the Year (YYYY).

- [ ] Once the date is selected in the middle, a text field to search through all diseases must appear. This text field must allow the user to type and search through any disease in ICD-11 (Internal Classification of diseases available at https://icd.who.int/en). The user must be able to find the right disease and select it. Enable multi Select
NOTE: ICD-11 is integrated into the "Diagnosis" field in CARE is #2016 

- [ ] Once the disease is selected, a long text description box must also appear.

- [ ] An option to add more sections of date, ICD and description must always appear below (Same design as the prescription module). This will allow users to keep adding more and more details about their medical history across various dates. 

DATA VISUALISATION 

- [ ] Once saved, fields will appear in Chronological order 

The design to be followed is indicated in the below design
<img width="342" alt="Screenshot 2022-08-09 at 1 31 26 PM" src="https://user-images.githubusercontent.com/67050716/183597060-8eb4c945-5ae5-4552-a259-e46d4d3f7ebc.png">

The larger "Medical History" section itself will only come expanded in the first consultation of a patient in CARE. In all other subsequent consultations, the section will appear minimized in the consultation form and will expand to show the content only when the user clicks on the header. 

- [ ] Additional Feature (may be separated out as a separate issue)
While viewing saved medical history, For every saved date, ICD and description, there needs to be an option on the right-hand side to "mark as cured". This will allow the system to not only list all the diseases the patient has but also understand which of them is already cured.

Part of #2218
@gigincg please review

**Comment by aparnacoronasafe** [comment]
Clarification on the revised content in patient registration form and consultation form
<img width="932" alt="Screenshot 2022-08-12 at 5 22 32 PM" src="https://user-images.githubusercontent.com/67050716/184350214-ef9ba8ce-98e3-42e2-a328-83e8a05e6b93.png">

**Comment by nihal467** [comment]
@cp-Coder Due to inactivity and the existing linked PR is not mergeable, unlinking you from this issue

As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by gigincg** [comment]
Closing in Favour of https://github.com/coronasafe/care_fe/issues/8388
