### ISSUE TITLE
Medicine Administration Record

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3437]
**Context**: 
We will be incorporating a more detailed module to track medicine administration for a patient inside the current I/O Balance within Log Update (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/80e1429f-4b91-44f2-9dbd-03c427920f54/update).

**Changes required:** 

- [x] Rename I/O Balance as "Administration Record" in critical care index (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/80e1429f-4b91-44f2-9dbd-03c427920f54/update)
- [x] Change the header of the I/O Balance section to "administration record (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/80e1429f-4b91-44f2-9dbd-03c427920f54/update)
- [x] The existing I/O balance will remain as a section within the page
- [x] Add another section on top called "Medicine Administration Record"
- [x] This section will contain the prescriptions already entered in the latest consultation. Both "Prescription and "PNR Prescription" in consultation (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/update) must be available here. (PNR prescription is yet to be merged #3194 )
- [x] The section will contain a table against each of the medicine in the prescription to note the administration of such a medicine. The table must contain simple checkboxes to note that the medicine is already given. These checkboxes must be in line with the "Frequency" suggested in the prescription.
- [x] For PNR prescription, instead of table to note administration, you can have a field to capture the time and date when it is administered. 

- [x] There should also be an option to Add more medicine. This must show the user all fields in the prescription module (in consultation). Once the user added details of a new medicine, the prescription in consultation must also be edited accordingly.

- [x] There must be an option to Discontinue a prescription by clicking on the red cross on the right side of each prescription. This must prompt a confirmation pop-up window stating "You are editing the treatment plan for the patient. Are you sure you want to discontinue the selected medication for the patient?"
Once discontinued, the medication must appear faded at the bottom with the name of Medication, dosage, frequency and administered from [date] to [ date]- these dates will be the date of first dose administered and the last dose administered. There must also be an option to restart the medication. 

A suggestive design is as below:

<img width="535" alt="Screenshot 2022-08-19 at 9 51 10 PM" src="https://user-images.githubusercontent.com/67050716/185663351-b56e1e14-e0b6-4bb8-8171-f3a856e02ea4.png">

**Comment by aparnacoronasafe** [comment]
Blocked since the relevant fields in consultation has not been added yet.

**Comment by aparnacoronasafe** [comment]
@skks1212 Hey. can you give me a quick update on the progress here?

**Comment by shivankacker** [comment]
@aparnacoronasafe was waiting for PRN to be merged before I take on this issue. Currently working on another critical care issue, will move on to this soon seeing required PRs have been merged

**Comment by aparnacoronasafe** [comment]
@skks1212 Why is this blocked Shivank?
