### ISSUE TITLE
Revamping Log Update

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3453]
The parameters dealt with in Log Update currently need to be relooked with more detail. 

The Log Update form needs to be separated out into 3 forms.
1. **Parameters recorded periodically**- This would consist of parameters like vitals which is recorded periodically like every hour or every 3 hours depending on the condition of the patient. These fields will be relevant throughout the ICU admission of the patient.
2. **Parameters recorded intermittently**- These parameters are noted down only if the need arises like ABG. However, this may be recorded repeatedly for a said period. However, the frequency may be lesser than vitals. These may be recorded daily or twice a day.
3. **Event based entries**. Done only when an event happens like nursing care, evaluating pressure sores etc. 

The sections in Log Update is identified into the above categories as under:
1. **Parameters recorded periodically**- Hemodynamic parameters (vitals), Neurological monitoring, Ventilator parameters, 
2. **Parameters recorded intermittently**- ABG, Blood Sugar, I/O balance (medicine administration record #3437 )
3. **Event-based entries**- Dialysis, pressure sores, nursing care.

The log update form may be split into the above 3 forms. @gigincg to add more details

**Comment by aparnacoronasafe** [comment]
More thought: Since 5-para monitors and ventilators and integrated directly to the device, isnt it better to keep both of those as separate forms. 

Do we have the bandwidth to develop and maintain 5 forms for log updates?

**Comment by gigincg** [comment]
Rethink/Refactor Daily Rounds from an Events perspective.

Need to add depth
cc: @vigneshhari

**Comment by gigincg** [comment]
Scope of Building:
- [ ] Rename DailyRound to Events in coronasafe/care
- [ ] Identify Event_Types & Recording_Types
- [ ] Add Event_Type & Recording_Type in DailyRound
- [ ] Create New DailyRound CRUD APIs
- [ ] Create Filters based on Event & Recording
- [ ] Rebuild Daily Round Creation UI
- [ ] Create Timeline UI

cc: @vigneshhari

**Comment by nihal467** [comment]
the entire module have been removed, reopen the issue after evaluating the requirement and current workflow
