### ISSUE TITLE
Improve how we consume icons in care

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3850]
As discussed in EOD and slack

- [x] Copy [`pf-icon`](https://github.com/pupilfirst/pupilfirst/tree/master/app/frontend/packages/pf-icon) implementation to care, so that icons that are not present in unicons can be added with the help of this.

## Tasks to be accomplished eventually: 
- [ ] Replace material ui icons.
- [ ] Replace fontawesome icons.

cc: @bodhish @skks1212 @gigincg
