### ISSUE TITLE
Facilities, Sample Tests, Shifting and Users pagination is not using query parameters

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#3955]
**Describe the bug**
Facilities pagination is not using query parameters like other pages such as the patients page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the facilities page
2. Go to page 2 using the pagination below
3. Go back to page 1 by pressing the browser's back button

**Expected behaviour**
Land back on page 1, instead of the page before reaching the facilities page.

**Screenshots**

https://user-images.githubusercontent.com/25143503/200097331-6d97df27-c871-43ba-901a-7bb19a030309.mp4

**Tasks**
- [ ] Pagination component to be responsible for setting query parameters.
- [ ] Update the Facilities page with the updated pagination component.
- [ ] Update the Assets page with the updated pagination component.
- [ ] Update the Sample Tests page with the updated pagination component.
- [ ] Update the Shifting page with the updated pagination component.
- [ ] Update the Users page with the updated pagination component.
