### ISSUE TITLE
Remove `classNames` and `clsx` package and use a utility function to achieve the same

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4076]
- [x] Remove `classNames` package.
- [x] Make a utility method `classNames`

### Migrating `clsx` to new `classNames` under the directories:
(sub-issues will be created to self-assign)

- [x] #4161
- [x] #4162
- [x] #4163
- [x] #4164
- [x] #4165
- [x] #4166
- [x] #4167
- [x] #4168
- [x] #4169
- [x] #4170

### Once all the above is completed:
- [ ] Remove `clsx` package
