### ISSUE TITLE
Cypress tests for few functionalities

### ISSUE THREAD

**Issue by GokulramGHV** [coronasafe/care_fe#4133]
Cypress tests are to be written for the following functionalities:

- [x] #4233
- [x] #4234
- [x] #5597
- [x] #5598
- [ ] File Upload on patient consultation
- [ ] Create a new log update on the consultation page
- [ ] update existing log update
- [x] #4235
- [x] create a new asset for a facility (PR: #4134 )
- [ ] configuration of the asset page
- [x] #4320
- [x] #4321

Google Sheets Link: https://docs.google.com/spreadsheets/d/1S77kcGMjVRgVlm9lA0WL2iV_GEhxs9xocm3ZD7p4uCY/

**Comment by ShivamJhaa** [comment]
@nihal467  All the unclaimed tasks depend on the open PRs like adding, and editing consultation can only be done after creating patients, and configuration of the assets page can be done after creating an asset. So can I take those tasks which are already assigned (creating an asset) as the PR seems stale now?

**Comment by khavinshankar** [comment]
@ShivamJhaa Yes, when you see a stale issue you are interested in, feel free to ask about the status of the issue tagging the assignees, if no one responds you can pick it up. And about the stale issue, you are talking about (https://github.com/coronasafe/care_fe/issues/4233), yes you can work on it

Just comment on the issue, so that you can be assigned to that issue

cc: @nihal467

**Comment by somesh202** [comment]
@nihal467 Can I take up the new asset creation issue as its PR seems stale now and would follow up by adding configuration of asset?

**Comment by nihal467** [comment]
@somesh202 comment is the PR and if the author doesn't reply back in 48 hours, you can take up the stale PR and work on it
