### ISSUE TITLE
Generalize the Download/Import/Export design to use Dropdown

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4252]
**Is your feature request related to a problem? Please describe.**
Currently the download / export of various pages does not have uniform design.

**Describe the solution you'd like**
Use consistent design: Dropdown Menu for Import/Export/Download buttons

**Tasks:**
- [x] Dropdown for Facilities (Export Facilities, Export Facility Capacity List, Export...)
- [x] Dropdown for Patients (Export and Import)
- [x] Dropdown for Assets (Export and Import)
- [x] Export Icon with Tooltip for Samples
- [x] Export Icon with Tooltip for Shift Requests
- [x] Export Icon with Tooltip for Resource
- [x] Dropdown for External Results (Export and Import)

**Additional context**

1. Facilities (to use Dropdown)
![image](https://user-images.githubusercontent.com/25143503/206439880-2a7cdcd4-9878-4404-8f75-2c880c4669a3.png)

2. Patients (to use Dropdown)
![image](https://user-images.githubusercontent.com/25143503/206440118-11a76d3b-b6dd-4ecf-8057-2f17ea73b042.png)

3. Assets (to use Dropdown)
![image](https://user-images.githubusercontent.com/25143503/206440245-734f98c8-0717-4ac7-8f93-90dad2e71c22.png)

4. Samples (to use export icon with tooltip)
![image](https://user-images.githubusercontent.com/25143503/206440566-fa59f763-2954-4984-8ae3-6d8780a5286d.png)

5. Shift Requests (to use export icon with tooltip)
![image](https://user-images.githubusercontent.com/25143503/206440659-838b4323-aacf-4d3e-b50f-3175011c452e.png)

6. Resource (to use export icon with tooltip)
![image](https://user-images.githubusercontent.com/25143503/206441003-56d8593c-e327-4524-85da-8810c07284cc.png)

7. External Results (to use Dropdown)
![image](https://user-images.githubusercontent.com/25143503/206440814-150d1afb-d8d7-4879-bb38-e4ef79a17b41.png)
