### ISSUE TITLE
Changes to shifting form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5300]
The shifting form (https://care.coronasafe.in/facility/d02ef2cb-b5b2-4baf-bc9a-fac348893b00/patient/fddf2473-bc46-403d-b450-b569ce29d997/shift/new) needs to be amended as below: 

- [x] "Contact person at the facility" to be edited to "Contact person at the current facility "
- [x] "What facility would you like to assign the patient to" field must also allow free text to type in names of hospitals outside the CARE Network.
- [x] Hide preferred vehicle
- [x] Hide preferred facility Type
- [x] Hide severity of breathlessness
- [x] Add patient category- to be autofilled with the last updated patient category in consultation form/log update. user must have option to revise it. (non-mandatory). field to come below "is this an upshift"
- [x] Add short text field for name of ambulance driver (non-mandatory). field to be placed after the reason for the shift
- [x] Phone ni. of Ambulance No.(non-mandatory)
- [x] Add short text field for Ambulance No. 

**Shifting approving facility**
- [x] The approval of the shifting approving facility must be given by default. This must be a "peacetime" configuration for any particular instance. During times of public health emergency, when the deployment goes into "wartime" operations, the manual approval by "Shifting approval authority" must be brought back. 
- [x] Wherever approval is made default, hide the field to select "Shifting approval authority" from the shifting request form.
- [x] When `patient expired` is selected as status and the changes are saved, Redirect the user to Discharge from CARE pop-up window, with the reason for discharge "death" must come auto-populated and must not be editable.

**Comment by aparnacoronasafe** [comment]
@Ashesh3 Todo No. 2.

**Comment by Ashesh3** [comment]
> @Ashesh3 Todo No. 2.

Todo 1-5 are completed in the linked PR.

**Comment by sainak** [comment]
@aparnacoronasafe @Ashesh3 I moved the last point from #5302 to this issue as it requires frontend changes as well
