### ISSUE TITLE
Discharged date in patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5315]
**Describe the bug**
When a patient is discharged with discharge reason as anything other than recovered, 
the discharged patients dashboard shows discharge date as Current date and not the discharge date mentioned in the discharge pop up window.

Eg: 
https://care.coronasafe.in/facility/4f885b99-9557-45b6-b696-0a851393dcdf/patient/931fdc5b-d460-4209-b11b-0576e74f78ae/consultation/06f7f97f-3111-4016-9d97-c276c6068cc7

The patient was discharged from CARE on 10/04/2023 by providing the following details in the discharge pop-up form:
Discharge reason: expired
date of death: 03/04/2023

Yet the patients' dashboard shows "Discharged on 10/04/2023"
<img width="1223" alt="Screenshot 2023-04-10 at 10 51 34 PM" src="https://user-images.githubusercontent.com/67050716/230955826-013d6ecf-f022-44ec-b4d2-2be757dc664a.png">

 
**To Reproduce**

1. Go to any patient
2. Click on "Discharge from CARE"
3. in reason for discharge, mention anything but recovered
4. and give any date other than current date in date of discharge

**Expected behavior**
The date provided in the pop-up discharge form must appear on the patient dashboard as the discharge date

**To-Do**

**When the discharge reason is expired,** 
- [ ] the patient dashboard to show "Admitted on XYZ, Expired on DD/MM/YYYY(date given in the pop up discharge form)"
- [ ] In the Discharge details card in the patient dashboard, remove Discharge date 
eg: https://care.coronasafe.in/facility/d02ef2cb-b5b2-4baf-bc9a-fac348893b00/patient/cc6294d5-3def-41e4-ae32-e4226debc517/consultation/6421550a-6be0-414d-9fbe-3b922471fd3b
<img width="411" alt="Screenshot 2023-04-10 at 11 00 24 PM" src="https://user-images.githubusercontent.com/67050716/230957564-912c8652-b8e3-4132-b830-f83f8b6a0a73.png">
- [ ] Add data validation to the date field in the discharge pop-up form: the date cannot be before the Admission date if there is an admission date (if not, date of consultation filed) or after the current date. Allow date of consultation/ Admission date.

**When the discharge reason is referred,** 
- [ ] the patient dashboard to show "Admitted on XYZ, discharged on DD/MM/YYYY(date given in the pop up discharge form)"
- [ ] In the Discharge details card in the patient dashboard, rename date to "discharge date and show the date given in the pop up discharge form
- [ ] In data validation to the date field in the discharge pop-up form: the date cannot be before the admission date (if there is no admission date, then date of Consultation filed )or after the current date. Allow date of consultation/ Admission date.

**When the discharge reason is LAMA,** 
- [ ] the patient dashboard to show "Admitted on XYZ, discharged on DD/MM/YYYY(date given in the pop up discharge form)"
- [ ] In the Discharge details card in the patient dashboard, rename date to "discharge date and show the date given in the pop up discharge form"
- [ ] In data validation to the date field in the discharge pop-up form: the date cannot be before the admission date (if there is no admission date, then the date of Consultation filed )or after the current date. Allow date of consultation/ Admission date.
