### ISSUE TITLE
Shifting revision- EPIC

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5393]
The shifting logic must work in the following way:

<img width="1373" alt="Screenshot 2023-04-24 at 11 29 58 PM" src="https://user-images.githubusercontent.com/67050716/234078498-a226b912-4643-4c78-b049-707f8308bb51.png">

Currently, there are many steps in the shifting flow. Since the same was designed to manage shifting during pandemic many additional checks were built in. 

We need to allow the shifting module to be configured for 
1) Peace-time
2) War-time

The steps involved in a shifting process need to be reimagined as

ACTIVE
1) Shifting approval pending (only relevant in war-time)
2) Patients to be shifted
3) destination approved
4) Transportation arranged
5) Patient in transit
6) Completed

ARCHIVED
7) Cancelled
8) Patient expired

We will first look at the Peace-time configuration and then discuss the additional features needed for War-time.

PEACE-TIME SHIFTING

- District admins and state admins shall have access to perform all functions on the Kanban Board. The access control of other users (staff and doctors) is as listed below:
1) All shifting requests created will automatically come into the "Patients to be shifted" list.
2) Both users linked to origin and destination facilities will have option to update status to "Destination approved"- the shifting request MUST have the destination facility filled. 
3) Only user from Origin facility must be able to mark status "Transportation arranged"
4) Only user from Origin facility must be able to mark status "Patient-in-transit"
5) Both users linked to origin and destination facilities will have option to update status to "Complete"- when the shifting status is marked as complete, the patient file automatically gets discharged from the origin facility. The discharge details are saved as - reason for discharge "referred" and discharge date as present date. Once the shift is marked as complete, the contents of the shifting form including the status must not be editable.
6) In the completed list, if the destination facility is a hospital within the CARE network, there must be an additional button on the patient card to "Transfer patient records" only visible to the users linked to the destination facility. Since this option is visible only in the complete list, we will already have the patient discharged. The "Transfer patient records" will move the records of the patient into the destination facility. Once the transfer is done, the botton should appear greyed out, to indicate that the patient records are already transferred. 
7) The users from the origin facility must be able to change status as canceled. Once canceled, the contents of the shifting form including the status must not be editable.
8) The user from the origin facility must be able to change the status as "Patient expired". When this is done, the user must see the discharge pop-up window with the reason for discharge set at expired (non-editable). Only when the user enters the remaining details of death in the pop-up window and submits should the status on shift be saved as "Patient expired" and the patient card must also be discharged as "Expired". 
9) The shifting KanBan board will have 2 sections " Active" and "Archieved" . Active board will have all cards till complete and achieved will have "cancelled" and "Patient expired"
- A new admission must automatically close (Move to canceled list if they are in any list other than complete) all pre-existing shifting requests.

WAR-TIME SPECIFIC FEATURES
- in war-time configuration, an additional step of shifting approval is necessary. "Shifting approval pending" will be the first status and the left most list in the Kanban board. Only when the configuration is set to war-time. The shifting request form must also have a field to add a "Shifting approval authority". Only users linked to such "Shifting approval authority" can edit the status of shift from the "Shifting approval pending" status to any other status.
- There shall be an option to "assign to" to assign the shift to particular users linked to "Shifting approval authority"
- The option "Is Karunya Arogya Suraksha Padhathi?" is relevant only during war-time 

To-do:

- [x] reconfiguring shifting steps and status coronasafe/care_fe#5394 
- [x] relooking at sections in shifting kanban coronasafe/care_fe#5395 
- [x] Clean up shifting request form coronasafe/care_fe#5390 
- [x] Default status of shift (peacetime) coronasafe/care_fe#5398
- [x] Marking shift as complete: coronasafe/care_fe#5389 
- [x] Cancelling shifting request coronasafe/care#1271 
- [x] ~~Transfer patient records- shifting: coronasafe/care_fe#5399~~
- [x] Covering edge cases in patient expired coronasafe/care_fe#5388 
- [x] Resolve bug with patient category coronasafe/care_fe#5387 
- [x] Power of admins coronasafe/care_fe#5385 
- [x] Ambulance No non-mandatory coronasafe/care_fe#5382 
- [ ] ~~Auto cancelling shifting request coronasafe/care_fe#5401~~

WAR-TIME FEATURES

- [x] Shifting approval-wartime coronasafe/care_fe#5397 
- [x] Assign to-shifting-war-time feature coronasafe/care_fe#5396
- [x] KASP only for war-time coronasafe/care_fe#5384

**Comment by nihal467** [comment]
close this issue, as everything marked are completed
