### ISSUE TITLE
Enhancements to Vitals Monitor

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5486]
**Pre-requisites and references:**
- https://github.com/coronasafe/care_fe/pull/5466

Currently, the Vitals Monitor has a fixed height and width, so cannot be used in the patient consultation dashboard as it would leave quite a lot of empty space.
![image](https://github.com/coronasafe/care_fe/assets/25143503/0ac22817-cfa4-4a75-be30-541001e65ae6)

**Tasks:**

- [x] https://github.com/coronasafe/care_fe/issues/2640
- [x] #5983
- [ ] Clear buffer on buffer overflow.
  This is so that we always show very recent information. Buffer overflow can happen when we change tabs, so the canvas render pauses. However, data coming from the web socket causes the buffer to get accumulated.
- [x] Make the Vitals Monitor's size configurable so that it can be used in the consultation dashboard too.
- [x] Refactor the component such that just passing a list of keys should be enough to articulate the non-waveform data (the data that are on the right side of the vitals monitor). BP and Temperature can be an exception (the data-type are a properly discriminated union)
  ![image](https://github.com/coronasafe/care_fe/assets/25143503/7826fbdd-7fb5-499f-9736-6af0620f853d)
- [x] #5984
  ![image](https://github.com/coronasafe/care_fe/assets/25143503/481870ee-4a77-4c9b-a382-43c8a196f8c9)

**Comment by Rohanxmalik** [comment]
I would like to contribute to this issue under C4GT. Please assign it to me.

**Comment by ishaanxgupta** [comment]
Hi @nihal467 @rithviknishad would like to work on this issue. please assign
Thanks
