### ISSUE TITLE
[C4GT] Redesign Doctor Notes

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#5493]
## Project Details:
CARE is a centralized capacity management and patient management system, central to the 10BedICU Project, integrating patients, doctors, hospitals, labs, specialized treatment centers, hospital administrators, and shifting control cells. Hospitals update crucial information about their assets, providing district administration with a comprehensive view of the healthcare system via smart dashboards. CARE digitizes patient records, streamlines workflows for pandemic management, and is deployed in remote areas, enabling Tele-ICU services for underserved citizens. It revolutionizes healthcare management, enhancing efficiency, accessibility, and patient outcomes.

## List of Features to be implemented

Doctor Notes in CARE is a feature that allows keeping notes specific to a Patient.  The goal of this project is to redesign **Doctor Notes** to improve its look and feel, as well as the user experience of it.

This can be redesigned keeping the following things in mind:
 - Notes should be shown in a chat popup ,expandable to a dedicated page.
 - New Notes should work as if they are Chat Notifications.
 - All the relevant parties should be notified of a new message.

###### What is a Doctor Note?

_Doctor note is a feature where doctors discuss a patient's condition, similar to a chat room. The doctor's note is specific to a patient, and it can only be accessed by going to the patient's existing active consultation file on the platform_

###### How is it used?

_To use it, go to the Patient tab, select the patient, and on the patient consultation page, click on 'Doctor note' located in the top right corner. You can then post your message or note._

###### Who will be using it, and will patients have access to this data?

_Doctors are the main users, who will be posting notes to discuss about a patient. and no patient will have access to these discussions_

###### In what scenarios is this feature used?

_This feature is typically used in scenarios where a patient in Facility A is experiencing rare symptoms, and the treating doctor wants to discuss the patient's condition with a doctor in another facility._

_Normally, patient files and conditions would be shared through mediums such as email, social networks, or voice communication before the discussion takes place. However, this can lead to a potential breach of confidentiality._

_In this scenario, the doctor from Facility A can share the patient consultation link with the doctor from the other facility. The second doctor can then view all the patient reports and information within the platform itself. Both doctors can engage in discussions using the doctor note feature, which functions like a chat._

_By utilizing this feature, all details and discussions remain within the platform. If they need to refer to their past discussions about the patient in the future, they can always access the doctor note of the specific patient, which will be available in their consultation._

## Learning Path
|  | Details |
| :---:  | :---:  |
| Complexity       | Medium |
| Required Skills | React, TypeScript, Django |
| Mentors            | @khavinshankar @rithviknishad @nihal467 @gigincg |
| Project Size      | 6 weeks |

## Link to documentation for Product Set-Up

1. For setting up the frontend, please refer to the readme file available at: https://github.com/coronasafe/care_fe
2. For setting up the backend, please refer to the readme file available at: https://github.com/coronasafe/care

## Acceptance/Success Criteria for the pull requests

1. All the cicd workflows should pass.
2. Code is logically structured for long-term project sustainability.
3. Proper descriptions should be included for review purposes.
4. QA and Code Review

## Milestones with timelines

- [ ] Get to know CARE as a product, and understand the workflow.
- [ ] Understand the field requirements and come up with a design.
- [ ] Design and implement the updated UI
- [ ] Complete functionality of chat like interface
- [ ] Optimise and improve UX
- [ ] Review and QA

**Comment by Drish-xD** [comment]
I'm interested in this project.

**Comment by PranshuNayak** [comment]
Hi @rithviknishad I'm Pranshu a pre-final year student at IIIT Jabalpur. I have prior experience working on ReactJs,Typescript and Django. I  am interested in this project and would like to contribute . Please let me know further steps to start contributing.

**Comment by rithviknishad** [comment]
You can get started by familiarising with the project with the help of good first issues present in the backend and front end repositories.

**Comment by pooranjoyb** [comment]
Dear @khavinshankar @rithviknishad @nihal467 @gigincg  ,

I am 3rd year undergrad from Manipal Institute of Technology (Sikkim), writing to express my keen interest in contributing to CARE as a ReactJS frontend developer. I want to assure you that I am highly proficient in building robust and user-friendly ReactJS frontends, and I am confident that my skills and expertise can greatly benefit your user-friendly frontend for Doctor Notes Component.

Here are some points that highlight my credibility and suitability for this project:

- **Extensive ReactJS experience:** I have a solid background in ReactJS development, with several years of hands-on experience in building dynamic and responsive user interfaces using React components, hooks.

- **Strong portfolio**: I have successfully delivered numerous projects involving ReactJS frontend development, and I have a portfolio showcasing my ability to design intuitive and visually appealing user interfaces. I am confident in my ability to apply these skills to create an exceptional frontend for Doctor Notes. [Here is my Portfolio](https://pooranjoyb.github.io/portfolio-website/)

- **Communication and teamwork**: I believe that effective communication and collaboration are vital for project success. I am a proactive team player, ready to actively engage with stakeholders, understand their needs, and translate them into intuitive frontend designs. I am confident that my interpersonal skills will contribute positively to the project's overall success.

I would be delighted to discuss the project further and showcase my skills in more detail. I genuinely look forward to the opportunity to contribute to CARE by redesigning the **entire frontend for the Doctor Notes** and ensuring an exceptional user experience and user interface.

I shall be glad if you guide me through the proposal submission procedure, eagerly await your response, Thanks.

**Comment by mustafaazad03** [comment]
Hi @rithviknishad, @khavinshankar ,
I am Mustafa Azad. Currently, I am MERN Stack Developer with significant experience in Python. As I have build notes and chat projects and implemented such functionality in the past and learned many efficient techniques to implement this functionality. This project grabs my interest and I would love to contribute in this.
It will be great if you provide some guidance.
Thank You

**Comment by Mounika-Pavanthi** [comment]
I am eager to contribute to the CARE project and be a part of the team working towards revolutionizing healthcare management. With my proficiency in JavaScript, Cypress, React, and TypeScript, I am confident in my ability to enhance the coverage of Cypress tests and ensure comprehensive testing of all functionalities. I am dedicated to delivering high-quality code, adhering to best practices, and actively participating in QA and code reviews. Please consider my involvement in the CARE project as I am enthusiastic about improving healthcare accessibility and patient outcomes.

**Comment by TechAtikiN** [comment]
Hello mentors, I am a Full Stack Developer and I am very interested in contributing to the project. The project aligns with the tech stack of my experience! Very enthusiastic about the project!
