### ISSUE TITLE
[C4GT] Add type safety to Teleicu Middleware

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#5495]
## Project Details:
CARE is a centralized capacity management and patient management system, central to the 10BedICU Project, integrating patients, doctors, hospitals, labs, specialized treatment centers, hospital administrators, and shifting control cells. Hospitals update crucial information about their assets, providing district administration with a comprehensive view of the healthcare system via smart dashboards. CARE digitizes patient records, streamlines workflows for pandemic management, and is deployed in remote areas, enabling Tele-ICU services for underserved citizens. It revolutionizes healthcare management, enhancing efficiency, accessibility, and patient outcomes.

## List of Features to be implemented

Middleware is an expressJS-based microservice to help tunnel CCTV Streams and ONVIF APIs for TeleICU. It gets the data streams from the hardware assets (like camera, ventilator, ...) and serves it to other services through rest APIs and web sockets.

Things to be done:
 - This microservice is fully written in javascript, which needs to be refactored into typescript.
 - Support sending asset status (live, down, not functional) along with the response.

## Learning Path
|  | Details |
| :---:  | :---:  |
| Complexity       | Medium |
| Required Skills | React, TypeScript, Django |
| Mentors            | @khavinshankar @rithviknishad @nihal467 @gigincg @mathew-alex |
| Project Size      | 6 weeks |

## Link to documentation for Product Set-Up

1. For setting up the middleware, please refer to the readme file available at: https://github.com/coronasafe/teleicu_middleware
2. For setting up the frontend, please refer to the readme file available at: https://github.com/coronasafe/care_fe
3. For setting up the backend, please refer to the readme file available at: https://github.com/coronasafe/care

## Acceptance/Success Criteria for the pull requests

1. All the cicd workflows should pass.
2. Code is logically structured for long-term project sustainability.
4. Proper descriptions should be included for review purposes.

## Milestones with timelines

- [ ] Get to know CARE as a product, and understand the workflow.
- [ ] Understand middleware and its functionalities
- [ ] Draft out types for models or entities in middleware
- [ ] Add status to model
- [ ] Review and QA

**Comment by PranshuNayak** [comment]
Hi @khavinshankar  I'm Pranshu a pre-final year student at IIIT Jabalpur. I have prior experience working on ReactJs, Typescript, NodeJs, ExpressJs and Django. I have already worked and implemeted middlewares in NodeJs. I would like to contribute on this project . Please let me know the further steps to start contributing.

**Comment by nipunarora098** [comment]
Hi @khavinshankar @PranshuNayak @brainless @giju @jitendraag,

I'm Nipun, a pre-final year student at LNMIIT, Jaipur. I have prior experience working with ReactJS, TypeScript, NodeJS, ExpressJS, and Django. I have successfully implemented middlewares in NodeJS before. I am excited to contribute to the CARE Middleware project and would appreciate your guidance on the next steps to start contributing. Looking forward to submitting the proposal for this one!

**Comment by Ayan-thecodeking** [comment]
Hello @khavinshankar @rithviknishad @nihal467 @gigincg @mathew-alex 
 I hope this message finds you well. I'm excited to express my keen interest in contributing to this project. After conducting a comprehensive review of the issue details, discussions, and codebase, I have found that my skills and experience align well with the project requirements. I have prior experience working with React.js, JavaScript, CSS, MySQL, and Docker. With my expertise in these technologies, I believe I can make valuable contributions to this project. I would greatly appreciate your guidance and support to ensure that I can deliver my best work. 🙌

**Comment by gurdeep-singh-3251s** [comment]
Hi,
Greetings @khavinshankar @rithviknishad @nihal467 @gigincg @mathew-alex 👋,
Gurdeep Singh Here - a 2nd year Student at IKGPTU.
I'm Currently learning and practicing Full Stack web development Daily.
It is a great opportunity for me to contributing in this project because it can enhance my technical skills though i'm currently working on the React, Typescript, Django and Python as well. And I hope and believe that, I am able to contribute really good in this project. By Contributing in this project i will really get a good exposure of open Source Contribution.  😊👨‍💻

**Comment by Mounika-Pavanthi** [comment]
I am eager to contribute to the CARE project and be a part of the team working towards revolutionizing healthcare management. With my proficiency in JavaScript, Cypress, React, and TypeScript, I am confident in my ability to enhance the coverage of Cypress tests and ensure comprehensive testing of all functionalities. I am dedicated to delivering high-quality code, adhering to best practices, and actively participating in QA and code reviews. Please consider my involvement in the CARE project as I am enthusiastic about improving healthcare accessibility and patient outcomes.

**Comment by nihal467** [comment]
@khavinshankar worked on it, waiting for review
