### ISSUE TITLE
Disable delete bed button if bed is occupied

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5513]
**Describe the bug**
If a bed is occupied the delete button is not disabled. https://github.com/coronasafe/care/pull/1312 disallows deletion of such beds.

**To Reproduce**

1. Go to a facilities location management page
2. Open bed management page of a location
3. Attempt to delete an occupied bed.

**Expected behavior**
The button should be disabled and a tooltip should be shown on why it is disabled.

#### Tasks
- [ ] Add chip/indicator whether a particular bed is occupied or not.
- [ ] Disable Delete bed button if bed is occupied.
- [ ] Show a tooltip saying its not allowed as it is occupied.
- [ ] Migrate html buttons in that page to use `ButtonV2` so that tooltip also can be added easily.

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/25143503/eabc4130-dd1d-4a11-97c1-49b4297987c9)

**Comment by Bhavik-ag** [comment]
Working on this !!
