### ISSUE TITLE
Remove usages of Legacy Components from `HelperInputFields.tsx`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5762]
### Tasks

- [x] Remove legacy components from `src/Components/Common/DiagnosisSelect.tsx`
- [x] Remove legacy components from `src/Components/Common/UserSelect.tsx`
- [x] Remove legacy components from `src/Components/Common/components/Switch.tsx`
- [x] Remove legacy components from `src/Components/ExternalResult/ExternalResultLocalbodySelector.tsx`
- [x] Remove legacy components from `src/Components/ExternalResult/ListFilter.tsx` (#5757 by @Ashesh3)
- [x] Remove legacy components from `src/Components/Facility/ConsultationForm.tsx`
- [x] Remove legacy components from `src/Components/Facility/DoctorCapacity.tsx`
