### ISSUE TITLE
Add cypress test for assets.cy.ts

### ISSUE THREAD

**Issue by ShivamJhaa** [coronasafe/care_fe#5835]
## Tasks

- [x] Test creating a new asset.
- [x] Update the newly created asset.
- [ ] Configure the newly created asset.
- [ ] Import a new asset.
- [x] Delete an already created asset.
