### ISSUE TITLE
Add test for patient_crud.cy.ts

### ISSUE THREAD

**Issue by ShivamJhaa** [coronasafe/care_fe#5865]
## Tasks

- [ ] Add consultation details of a newly created patient.
- [ ] Edit consultation details of an already-created patient.
- [ ] Create Patient shift requests.
- [ ] Post doctor notes for an already created patient.
- [ ] Create and verify the generated treatment summary.
- [ ] Edit prescriptions for a patient.
- [ ] Discharge a patient.

**Comment by nihal467** [comment]
@ShivamJhaa 

- admission consultation creation is already in the test, do re-verify it, 

Add the below things to the file as well

- [ ] You can create a test to create non-admission consultation for a patient
- [ ] verify details submitted during consultation creation are reflected properly on the patient consultation dashboard
- [ ] create and verify the generated investigation summary
- [ ] upload file to patient dashboard
- [ ] create normal and critical log-update for a patient and verify all data are reflected
- [ ] along with editing prescriptions, bulk administrating, and discontinuing the medicine
- [ ] along with creating a patient shift request, add the test to update patient shift status updation and when the patient is marked completed, they are successfully discharged from existing facility
