### ISSUE TITLE
Decision After Consultations: Deprecate "Home Isolation" and show Admission Date field for "Home Care" / "Domiciliary Care"

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5940]
The following changes are required for the Decision after Consultation in the Consultation Form

### Tasks

- [x] "Home Isolation" should be deprecated.
- [x] "Domiciliary Care" / "Home Care" should ask for `admission_date` (labeled as "Start date").
- [ ] Add/update necessary backend validations for the same.

**Comment by aparnacoronasafe** [comment]
Looks good @rithviknishad

**Comment by rithviknishad** [comment]
Ack
