### ISSUE TITLE
User activity tracking

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5957]
To understand the utilisation pattern on CARE, Start tracking the following information about users in CARE:

1) NURSES (Staff)

- [ ] No. of patient registrations done
- [ ] No. of consultations filed
- [ ] No. of log updates filed
- [ ] No. of edits made to the patient profile
- [ ] No. of edits made to consultations
- [ ] No. of edits made to log updates
- [ ] No. of medicine prescriptions filed
- [ ] No. of edits made to the medicines
- [ ] No. of MAR (medicine administration record) created
- [ ] No. of file uploads done
- [ ] No. of investigations filed
- [ ] No. of shifting requests raised
- [ ] No. of time Doctor Connect is accessed
- [ ] No. of times CARE CNS accessed

2) DOCTOR

- [ ] No. of consultations filed
- [ ] No. of edits made to consultations
- [ ] No. of medicine prescriptions filed
- [ ] No. of edits made to the medicines
- [ ] No. of times patient profile visited (patients within home facility and remote facility to be identified differently)
- [ ] No. of time Doctor Connect is accessed
- [ ] No. of times patient camera feed accessed (patients within home facility and remote facility to be identified differently)
- [ ] No. of file uploads viewed
- [ ] No. of TeleICU Doctors notes filed (patients within home facility and remote facility to be identified differently)

All this information to be tracked on CARE and must be made available on metabase

**Comment by bodhish** [comment]
Closing this as the issue is blocked for over an year
