### ISSUE TITLE
Phase out `moment` package

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5977]
With ref. to 

- https://momentjs.com/docs/#/-project-status/
- https://bundlephobia.com/package/moment@2.29.4
- https://bundlephobia.com/package/dayjs@1.11.9

### Tasks

- [ ] Identify all moment usages in care, to understand what functions of moment would have to be recreated using javascript's `Date` object.
- [ ] Use an alternate package (maybe `day.js`) or better use `Intl` library itself based on the scope of work
- [ ] Replace existing usages of moment and uninstall moment
