### ISSUE TITLE
Tracking Expiry of AMC/Warranty in CARE

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6241]
**Is your feature request related to a problem? Please describe.**
In Asset management module we collect date of expiry of AMC/warranty of an asset. However there are no others features for users to get notified of when AMC/warranty is expiring soon.

**Describe the solution you'd like**
Introduce 2 kinds of alerts for AMC/warranty expiry.
**Yellow Alert**- starts 3 months before expiry and changes to a 
**Orange Alert** - starting 1 month before expiry
After Expiry of AMC/Warranty, a **Red Alert** must show till the AMC/warranty expiry date is updated to a future date.

- [ ] Show label on Asset list (https://care.coronasafe.in/assets) and asset page (https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/fe3295e6-0893-4024-99a8-3f2b981ea1c6) for 
- "AMC/Warranty expiring soon"- in yellow and orange colours respectively
- "AMC/Warranty expired"- in red colour.

- [ ] Add filter for "AMC Warranty Status" and have options (Multi-select) to show: 
- Expired
- Expiring within 1 month
- Expiring in 1-3 Months
- Expiring in 3-12 Months
- Expiring in 12-24 Months

- [ ] Notification must go to all Users for AMC/Warranty expiry.
- Create a new type of Notification. "Asset- AMC/Warranty"
- As and when 1 or more assets' AMC/Warranties are due to expire in 1-3 months the Notification must read as below:
HEADING: AMC/Warranty expiring in 3 months! 
BODY: AMC/Warranty for 15 Assets are expiring in 3 months. Contact vendor to extend AMC/Warranty now.
"Open" button should lead user to the asset list with filter showing "Expiring within 1 month" and "Expiring in 1-3 Months"
Its good to also show a Yellow alert Icon on the notification.
- As and when 1 or more assets' AMC/Warranties are due to expire in 1 month the Notification must read as below:
HEADING: AMC/Warranty expiring in 1 month! 
BODY: AMC/Warranty for 15 Assets are expiring in 1 month. Contact vendor to extend AMC/Warranty immediately.
"Open" button should lead the user to the asset list with filter showing "Expiring within 1 month" 
Its good to also show an Orang alert Icon on the notification.
- When 1 or more Assets' AMC/Warranty expires, send a similar notifications alerting that AMC/Warranties of so many assets have expired in a similar fashion with Red Alert icon
- If there are 1 or more expired AMC/Warranties, on 1st of every month send a notification with No. of assets with expired AMCs warranties with Red Alert icon

**Comment by GokulramGHV** [comment]
@aparnacoronasafe @nihal467 Is this okay of the expiry labels?
<img width="1185" alt="image" src="https://github.com/coronasafe/care_fe/assets/40627011/574a9a8f-a872-48bf-a07d-800efdad3ee5">

**Comment by aparnacoronasafe** [comment]
@GokulramGHV I discussed with @bodhish 
Notification will be hard to deploy.

Lets skip notification for now
