### ISSUE TITLE
Asset Module : Remaining Cypress Test

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6257]
![image](https://github.com/coronasafe/care_fe/assets/57055998/67fcb752-a337-4e35-b509-498f48ce450f)

**Add Test to Asset_tab** 

- [x] Rename Asset_tab to Asset_Homepage
- [x] #6265
- Add verification for the asset card with that name present & and the badge appears after the search
- Add a test to search by QR ID and Serial Number with a similar approach as the search by name test
- [x] #6267
- Add Badge verification for the applied filters
- Add URL verification that the badges are applied
- Click the clear button and verify all applied filters are cleared
- Click the back button and make sure that it works as expected and doesn't clear any applied filter

---

**Add Test to Asset_Creation**

- [x] Create a new file Asset_Creation and move all tests in asset_manage to this file except asset delete
- [x] #6290
- [x] in the already existing import asset test,
- add test to verify the imported asset is reflected in asset tab
- [x] In the already existing Edit asset test,
- add test to verify the updated detail reflected in asset tab and asset detail page
- [x] #6307
- to create asset page is proper
- to view the asset page properly along with the badge in the asset tab page showing particular facility name

---

**Add Test to Manage_asset**

- [x] #6348
- [x] add a new test to add a new asset service history, edit the service history, and verify the reflection of the same in the asset detail page
- [x] In the already existing delete asset test, verify the deleted asset is not present in the asset tab
