### ISSUE TITLE
Consultation Form: Refactoring "Status during consultation"

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6280]
- [x] https://github.com/coronasafe/care/issues/1662
- [x] https://github.com/coronasafe/care/issues/1671

**Comment by rithviknishad** [comment]
@aparnacoronasafe to suggest the order of these options based on relevance

**Comment by aparnacoronasafe** [comment]
- [ ] Rename the field from "Status during consultation" to "Route to Facility"

- [ ] Rename "Outpatient (walk-in)" to "Outpatient/Emergency Room"

- [ ] Change options to below: from top to bottom, show:
- Outpatient/Emergency Room
- Referred from another facility
- Internal Transfer within facility


- [ ] Migrate and map existing Data:
- All brought dead is merged with "Outpatient/Emergency Room" (since any new patient, alive or dead is brought to hospital through ER)
- Transfer from ward and transfer from ICU to be merged into "Internal Transfer within facility" 
- Referred from other hospital changes to "Referred from another facility"

- [ ] If "Referred from another facility" is selected, Field for 
- "Name of referring doctor" <Short text field> - non mandatory
- "Name of referring facility" <Short text field> - Mandatory
- "Date and Time of admission to ICU"- <Date, time picker>-  non-mandatory

- [ ] If "Internal Transfer within the facility" is selected, 
- Date of admission to this facility <Date picker> - Mandatory
- "Date and Time of admission to ICU"- <Date, time picker>- non-mandatory
- Name of Ward/ICU the patient is shifted from: <Dropdown with all locations in the facility> - Mandatory

**Comment by nihal467** [comment]
- [ ] Discussed in EOD, both Time and date of admission is mandatory
- [ ] Existing data should not have time

**Comment by rithviknishad** [comment]
@aparnacoronasafe If we merge "brought dead" with "outpatient", we'll no longer be able to know which all patients were brought dead (even for existing consultations).

A better alternative would be to show "Outpatient/Emergency Room" itself in the dropdown (without brought dead in the dropdown), however, if the user selects "outpatient", a checkbox would appear below whether the patient was "Brought Dead" or not. For other dropdown options, this brought dead checkbox would stay hidden.

This way we won't lose the clarity on our existing data.

What are your thoughts?

**Comment by rithviknishad** [comment]
Same suggestion for the Internal Transfer within the Facility (ICU/Ward)

We could do like: if the user selects "Internal transfer within facility", another dropdown can be shown to select ward or ICU beside "Name of the Ward/ICU" text field.

Merging options would mean we would lose the level of detail from the existing data too.

**Comment by rithviknishad** [comment]
something like this: 

<img width="405" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/cd3c543a-6adc-481a-bb19-12e67124ba10">

<img width="416" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/f46de325-de85-41ea-aa5d-787f569c0788">

**Comment by rithviknishad** [comment]
Also, should the Name of the Ward/ICU field be a select dropdown that the user can select from the list of locations available in that facility? Or should it simply be a text field?

**Comment by rithviknishad** [comment]
As discussed: 

- Brought Dead can be merged with Outpatient since all such records' Decision after consultation is already set to "Declare Death", so no information is lost even if merged.
- Transfer from ICU and Ward can also be merged. The Name of ICU/Ward would be a Facility Location select dropdown, and later on we can allow a location to be classified as ICU/Ward instead.
