### ISSUE TITLE
Remaining Cypress Test in Facility Module

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6653]
**Facility_Home**
---

- [x] Create a Test to verify the Export Functionality of the facility homepage ( Related Functionality + API Verification ) #6730 
- [x] Create a Test to search facility on the homepage ( Related functionality + API Verification + Query Parameter Verification ) #6733 
- [x] Create a Test to check Functionality of Facility advance filter ( functionality + Verify Facility Name post filter + Badge function ) #6736 
- [x] Create a test to check page navigation on Facility page ( Functionality + Query Params Verification + Facility Card Verification ) #6912 
- [x] Create a test to check facility card button redirection to Specific page, and back   ( Functionality + Query Params Verification + Facility Card Verification ) #6912 

**Facility_Create**
---

- [x] Convert Existing Create Facility test to POM and modify it to create facility with and without bed capacity and doctor capacity during the creation process ( Functionality + URL + API + Facility Detail page data reflection verification ) #6785 
- [x] Convert existing  update facility test to POM #6792 
- [x] Create a new triage and verify multiple triage on same day along its data reflection #6795

**Location_Management**
---

- [x] Convert Existing Create Location test to POM approach and cover the following : #6907 
1. Add new location functionality along with middleware and description | Verify the reflection 
2. Edit the newly creation location | Verify the reflection

- [x]  Create a test to create bed using multiple bed option and single bed option #6907

1. Verify the vacant and particular bed badge presence
2. delete functionality of a bed and verify it

- [x] Create a test to verify error throwing for duplicate same bed creation #6912 

**Inventory_Management ** https://github.com/coronasafe/care_fe/pull/6979
---

- [x] create a new inventory and verify low stock based on backend fixed data
- [x] create a new inventory and verify add/remove stock based on frontend low stock
- [x] create a test to manage mark as accident and the whole process

**Facility_Manage**
---

- [x] Convert the existing test to configure a facility and add home facility id along with it #7040
- [x] create a test to upload, modify and delete a facility cover image #7039 
- [x] Create a test to modify facility existing bed capacity #7056 
- [x] create a test to modify facility existing doctor capacity #7054
- [x] convert existing delete facility test #7057 
- [x] verify the facility detail page present buttons are properly redirecting to each page #7057
