### ISSUE TITLE
Rename `admission_date` to `encounter_date` and white label the field based on decision after consultation choice

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6668]
**Tasks**
- [ ] Rename variable name `admission_date` to `encounter_date` (to make it more generic and suitable for use while being agnostic of the decision after consultation choice)
- [ ] `encounter_date` should be captured for all types of "Decision after Consultation" choices and is a mandatory field.
- [ ] The "Admission Date" field label should be white labelled based on the selected Decision after Consultation / `suggestion` option. Similar to how we do now for Domiciliary Care (we label the `admission_date` variable as "Domiciliary Care start date")
