### ISSUE TITLE
Hide "Asset Type" (Assets to be always "Internal")

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6789]
Asset classification as "External" asset is no longer used.

### Tasks
- [ ] Remove "Asset Type" select input from asset create/edit form.
- [ ] Upon creating an asset, it should always create with asset type as "Internal"
- [ ] Remove it from the asset details page too.
- [ ] Remove Asset Type filter from Advanced Filters

**Comment by shyamprakash123** [comment]
I want to work on this can you assign this to me?
