### ISSUE TITLE
Consultation Specific route for Doctor Notes

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6818]
**Describe the bug**
https://github.com/coronasafe/care/commit/1ce8fdceea9fb9b00788e586662f8d871a292e22 added support for doctor notes to be consultation-specific. However, the front-end still shows notes from all consultations.

**To Reproduce**

1. Go to https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/notes
2. See error

## Tasks

- [ ] Add doctor notes route to be consultation specific. Currently, it is of: `/facility/id/patient/id/notes`. It should be `/facility/id/patient/id/consultation/id/notes`
- [ ] Doctor notes from that route should show doctor notes only for that consultation.
- [ ] However, Patient Notes opened from Patient Details page should show all notes, this can retain the current route itself instead. (Maybe we could indicate which consultation the note belongs to in this view, maybe as a chip showing the consultation admission date + facility name or something similar which when clicked would take you to the consultation details)

**Comment by sainak** [comment]
Some notes don't have a consultation linked to them
So we should display all notes for a patient I. The patient details page

cc @Ashesh3 @rithviknishad
