### ISSUE TITLE
Support for deleting a location

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6976]
**Describe the bug**
Currently, there's no way to delete a Location of a facility from CARE.

**To Reproduce**

1. Go to the Location Management page

**Expected behavior**
Ability to delete a location

## Tasks

- [ ] Add a delete button to the location edit form
- [ ] Support DELETE method for location detail API.
- [ ] API should reject with the valid reason specified if some assets or beds are not deleted from a location.
- [ ] If there are assets in the location, prompt the user to delete existing assets in that location and show a link to navigate to the page where assets are filtered by that location.
- [ ] Similary for beds. Prompt the user and link to navigate to the bed management page of that location.
