### ISSUE TITLE
Remaining Cypress Test for Patient Module

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7058]
**Note:** Please refrain from assigning this EPIC to yourself. Sub-issues must be expanded before any further action is taken. If you wish to work on a specific part, please comment on this issue indicating which section you'd like to handle. Once the sub-issue has been created by the core team and assigned to you, you may proceed with your work.

**Patient Registration**
---

- [x] Patient Registration with all field then verify its reflection in detail page and list view 
- [x] Patient details updated and verify it's reflection in detail page #7107 
- [x] Patient registration with mandatory field, consultation and no medicine data then verify all consultation detail only
- [x] Transfer a patient with number and create consultation with medicine then verify all medicine presence #7165 
- [x] Patient with multiple status of route facility #7246 
- [x] Patient with multiple status after consultation #7246 

Note for personal reference : Make patient registration as a multiple combined function 

**Patient Detail Page**

---

- [x] #7086
- [x] #8769
- [x] #8913
- [x] #8914
- [x] #8926

**Patient Manage**

---

- [x] #8768
- [x] #7558
- [x] #7334
- [x] #8069
- [x] #7728
- [x] #8669
- [x] #8543
- [x] #7555
- [x] #8544
- [x] #7763

**Patient Homepage**

---

- [x] #8545
- [x] #8546
- [x] #8547

**Comment by MjStar24** [comment]
hey @nihal467 @rithviknishad I would like to work on this can you assign this to me

**Comment by nihal467** [comment]
non-relevant to current develop
