### ISSUE TITLE
Support for global search and filters in CARE

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#7277]
**Is your feature request related to a problem? Please describe.**
Currently, to search for patients, assets or facilities, we have to go to its corresponding list page and search. We could improve the experience by providing a global search that can be used to search any of those.

**Describe the solution you'd like**
- [ ] Open up a global search bar upon the keyboard shortcut.
- [ ] When no filters are applied, the user could be prompted with available searches. "Search patients" / "Search facilities" / "Search assets" / etc.
- [ ] Once the master search is selected, additional filters can be applied (see screenshot below)

_Support for searching and filtering facility/assets/patients, each module can be added in separate PRs as a follow-up to the first implementation._

**Additional context**

- We could use the following rescript component

Ref: https://www.npmjs.com/package/@pupilfirst/multiselect-dropdown
Preview: https://multiselect-dropdown.pupilfirst.com/

<img width="999" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/44e1634b-b5d5-4a2c-ab3a-d6889ea08ec0">

<img width="1162" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/fb7dddb6-c13c-4c17-8289-34147e0a6e3e">

- Tailwind CSS's global search bar

<img width="1002" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8a9745f1-1cbe-453d-b7f7-6bebd4a5d68c">

**Comment by SinghYuvraj0506** [comment]
Hey, it seems a very nice idea, we can add a feature like spotlight search offered by ios , where we can type various tags and as one presses enter that particular tag would be selected, or even we can provide some custom inputs in the spotlight like 
field:value pair tags,

for example  tags could be like:
1. Search for : facilities / patients / assets
2. location : Delhi/city
