### ISSUE TITLE
Upgrading Sample Tests & Investigations to Lab Orders for LIMS

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#8683]
### Roadmap 
_subjected to change while working on it_

#### Frontend

- [ ] UI/UX Design
- [ ] Pages and Components
	- [ ] Create Service Request Page (form view)
	- [ ] List Page (with tab view of the following)
		- [ ] List Service Request (table view)
		- [ ] List Specimen (table view)
		- [ ] List Diagnostic Report (table view)
	- [ ] Flow Page (timeline view of each step)
	- [ ] Result Page (descriptive view of Diagnostic Report)
- [ ] Wiring the above UI with the backend

#### Backend

- [x] https://github.com/ohcnetwork/care/issues/2646 (Basic backend flow)

##### Remaining
- [ ] Create filters based on flow status
- [ ] Wire the basic flow (till the lab technician adds the results)
- [ ] Aliquot creation (add required APIs)
- [ ] Map observations required for lab order code
- [ ] Pathologist review flow
  - [ ] Task specs and model
  - [ ] Reorder tests
- [ ] Add a way to track Laboratories (Users and Services offered)
- [ ] Permissions
- [ ] Tests
- [ ] Migrate existing data

**Comment by khavinshankar** [comment]
No longer relevant
