### ISSUE TITLE
Issues in the new branch of CARE do deployment

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9471]
# Summary Of Features Implemented So Far In New DO Branch

- [x] Public search for facilities
- [x] Public facility page
- [x] Public appointment scheduling
- [x] Patient login
- [x] Scheduling and Availability for all resources
- [x] Services request support for patients
- [x] Support for dynamic questionnaires
- [ ] HL7 complaint EMR modules for capturing and storing patient data and their views
- [ ] Value set support and Snowmed, Loinc, ICD10 integration
- [x] A lot of cleanup in facility
- [x] Removed sample management fully

---

# Workflow's

We are having multiple Workflows in places, use the below link to view bugs in each of them and entire workflow can be viewed using this [link](https://ohcnetwork.notion.site/Palliative-Care-Process-Flow-c0f7816c7b854ef69c5c1cb658b32fa9#42d3b2aeebb347bbb8d0b67d159c73b1)

[Workflow 1](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549511479) | [Workflow 2](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549526634)  | [Workflow 3](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549981751) | [Workflow 4](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549985845) | [Workflow 5](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549986654) | [Workflow 6](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549987685) | [Workflow 7](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549988968) | [Workflow 8](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549989787) | [Workflow 9](https://github.com/ohcnetwork/care_fe/issues/9471#issuecomment-2549990325)

---

# Login-Credential

**Districtadmin:** nihal-admin p/w : Test@123
**Doctor:** nibras-doctor p/w: Test@123
**Nurse:** ramya-nurse p/w: Test@123
**Volunteer** vaishnav-volunte p/w: Test@123

**Comment by AdityaJ2305** [comment]
Hey @nihal467, I’d like to pick up some issues from here. I’ve successfully branched out this branch locally.

**Comment by nihal467** [comment]
# Workflow 1

![Image](https://github.com/user-attachments/assets/770c9823-25b2-44f3-a913-a2b6ffcb0898)

---

## [Users Login Page](https://care.do.ohc.network/facility/)

![Image](https://github.com/user-attachments/assets/ea3ea4bd-74e0-4397-bad9-d7ffca7b2971)

### Major issue

- [ ] The patient login using the phone number OTP is not being generated to the user

Note: the AWS sandbox services we are using require to register the number with the services first, then only the OTP generation will work in the CARE. For now, we can use the static OTP : 45612

- Login with the static OTP is also not possible

### Minor Issue

- [x] add the translation to the username and password error message in the staff login
- [x] add the translation to the OTP sent successfully notification for the patient login section

![Image](https://github.com/user-attachments/assets/86cdcaff-71ad-40c8-a876-30ce64cc9812)

- [ ] Add proper error message for incorrect OTP-based patient login on the homepage

---

## [Facility Public Page](https://care.do.ohc.network/facilities?state=1&facility_type=840&page=1&limit=14)

![Image](https://github.com/user-attachments/assets/cceaf63f-7c41-4a27-b22d-228d0e1221e9)

### Minor Issue

- [ ] The Facility Type advanced filter on the Facility Public Page is not working because the facility type details are not shown on the card. We can either hide the filter or display the facility type details on the card and fix the related filter functionality. 

![Image](https://github.com/user-attachments/assets/97c3664a-c416-4a3c-885e-02888d00d790)

- [ ] the pincode-based search is not working, as well as the pin code are not visible in the facility details page

![Image](https://github.com/user-attachments/assets/ef7eba78-cca4-4956-a1af-94048104b126)

- [ ] rephrase the sentence properly instructing the user to login

### Enhancement

- [ ] Add a back button to the facility public page, which users can use to go back to the initial district selection [page](https://care.do.ohc.network/)
- [x] Add a login button of the right side top corner, so users can always go to the login page from the public page

---

## [Facility Details Page](https://care.do.ohc.network/facility/0aef5488-ea4d-4280-938a-d6b2fb44df59)

![Image](https://github.com/user-attachments/assets/1de0bb78-9cd9-40f0-ae41-ed2b530e728a)

### Minor Issue

- [ ] Only show the doctor users in the facility detail public page for booking appointments, as they are the only users who will be requiring a appointment book (Product Discussion Required)

### Enhancement

- [ ] Add support to search the doctor's name / Qualification in the facility details page

---

## Booking Appointment

### Major Issue


![Image](https://github.com/user-attachments/assets/9f63382a-61e1-4872-88ac-6f59ecea5340)

- [ ] add a validation , to restrict users from deleting existing schedule, if already anyone of the available slots are in use

![Image](https://github.com/user-attachments/assets/bd5e4e26-613e-4dcb-9509-78bb63f54cd3)

- [x] We can use an invalid OTP such as 00000 to login to the appointment portal and register a patient, even though the frontend throws a 400 error, so handle the situation with proper validation and gracefully

### Minor Issue

![Image](https://github.com/user-attachments/assets/020ff3a4-6fa9-4de8-b3a0-c00e55a9fd9c)

- [x] Add fine text for age mentioning to the user that, only the year of birth will be saved if they are using the age field

![Image](https://github.com/user-attachments/assets/9d564f5d-6361-48c4-9595-19b0f604edcc)

- [ ] Add support to the current address field allowing users to type address in multiple lines

![Image](https://github.com/user-attachments/assets/4ed2dee4-b32b-4cb9-a330-4f30fc010d25)

- [ ] Add validation for DD MM YYYY field to check whether each field is having respective number of digits for each input fields

---

## [User Details Page](https://care.do.ohc.network/users/nibras-doctor/availability)

### Major Issue

![Image](https://github.com/user-attachments/assets/b34ef0cc-508c-4859-ac39-3a0098dfe80d)

- [x] When we try to create an availability schedule for a user, **without mentioning the weekly schedule**, submitting the form crashes the page. Additionally, each time we open the Availability section on the user's detail page of the same user, the page kept on crashing

![Image](https://github.com/user-attachments/assets/03737a76-dc76-4e56-b141-be84d76c1cc3)

- [ ] When we try to create a schedule exception for a user, its throwing 404 error in the frontend

### Minor Issue

![Image](https://github.com/user-attachments/assets/4c4c0189-5abd-4be4-98b6-8e1953064ba9)

- [ ] Replace the return to care button located under the no home facility icon with Return to Linked Facilities
- [ ] Repositon the icon and button of no home facility so, we can avoid unwanted scroller in this page

![Image](https://github.com/user-attachments/assets/803a381d-550b-4eb3-bd36-09670e69f4d5)

- [ ] When there is no exception available for a user, the loader is keep on loading infinitely

![Image](https://github.com/user-attachments/assets/4f02df1a-dac5-4423-a4e0-13214ac2b216)

- [ ] The weekly schedule field in the create schedule template form is not properly responsive

![Image](https://github.com/user-attachments/assets/d779635f-d7e5-4c8b-b295-3f0e36a69882)

- [ ] the info card in the session section of create schedule template is not properly responsive

![Image](https://github.com/user-attachments/assets/81348104-31c2-489d-914a-b04c34e174a3)

- [ ] the return to CARE button in the crashing page is not redirecting properly to the loginpage 

### Enhancement

![Image](https://github.com/user-attachments/assets/188d19c0-c3ae-47ce-98ab-ab085fae4182)

- [ ] Add an option to edit the existing schedule template of the user

![Image](https://github.com/user-attachments/assets/babb2266-3cb6-4152-9eb0-3ed3981dd831)

- [ ] Use color coding for the dates to clearly indicate their availability status—such as available, fully booked, nearly full, and unavailable—making it easier to understand availability at a glance without needing to click on each date.

**Comment by nihal467** [comment]
# Workflow - 2

![Image](https://github.com/user-attachments/assets/1cdc4bb9-edaa-4555-acf6-b01663ab596c)

---

## Appointment Dashboard

### Major

![Image](https://github.com/user-attachments/assets/fa739c7c-788a-45cc-897b-337684c505e4)

- [ ] Multiple schedule API's are failing in the appointment tab and throwing something went wrong in the frontend
- [ ] the appointment dashboard cards are not filtered based on the selected doctor
- [ ] The patient card in the dashboard should display the patient's DOB or age instead of "undefined."

![Image](https://github.com/user-attachments/assets/06d69b48-b6a5-4e2d-9e78-c5e4908a01b5)

- [ ] when we click on the appointment card, we are being redirected to a patient details page with no info, ideally user should be redirected to a page, where they can view details filled during appointment, view , edit or delete the appointment

![Image](https://github.com/user-attachments/assets/c0076425-c704-43b7-b7a3-8cb625f6e869)

- [ ] When we visit the doctor consultation page from the patient details page using the top-right corner button, the slot API fails to load the available slots for the day in the doctor consultation page

### Minor

- [ ] Currently, the view remains stuck on the board view and does not switch to the list view, even when attempting to change it.
- [ ] The patient name-based search functionality in the dashboard is not working.

### Enhancement

- [ ] The appointment dashboard should allow users to filter the cards based on a date range.
- [ ] Add support for special priority tokens based on factors such as age, post-operation revisits, or any other external reasons.


## Patient Consultation Dashboard

### Major

![Image](https://github.com/user-attachments/assets/a5afc052-6569-468b-9be7-b653272a9faa)

- [ ] The symptoms and diagnosis are not displayed on the patient consultation page, even though the data is available.

![Image](https://github.com/user-attachments/assets/a247ab80-1789-4966-ba5f-4f672b15ee69)

- [ ] the questionnaire present in the log update is not at all mobile responsive

![Image](https://github.com/user-attachments/assets/15201b36-3fe0-4143-8241-83e1cbe50ba7)

- [ ] the questionnaire is not closing post-submission of the data

![Image](https://github.com/user-attachments/assets/5c4cbde9-65dc-48ab-86e8-bd7f7077ad03)

- [ ] Even though the data from the questionnaire is being saved, the related graph and reflections in the Patient Consultation Dashboard are not being populated with the data.

### Minor

- [ ] Add missing translations for no observation and no questionnaire

![Image](https://github.com/user-attachments/assets/795426d9-2747-4f06-929c-3bab6266886c)

- [ ] We have no individual text box for each nursing care

**Comment by nihal467** [comment]
# Workflow 3

![Image](https://github.com/user-attachments/assets/ddc3196d-ff4b-40a3-aade-e29a24c77f37)

---

## Major Issue

- [ ] Add an option to update the resource category in the update details form
- [ ] Add an option to cancel an existing request and add a note column as well to record why are they cancelling it

### Minor Issue 

![Image](https://github.com/user-attachments/assets/3ce4f503-64a3-42a4-b3dd-97f020983460)
![Image](https://github.com/user-attachments/assets/51948eab-6b52-44b3-aab6-7b8c13323127)

- [ ] Replace the colour of the resource request button to use primary colour to keep it consistent with other button
- [ ] Replace the colour similarly in the resource request details page as well

![Image](https://github.com/user-attachments/assets/2de9e4a4-31cd-4599-a36d-13a70e7b0a64)

- [ ] Add necessary translation to all options in the resource request form

**Comment by nihal467** [comment]
# Workflow 4 {Work in progress}

![Image](https://github.com/user-attachments/assets/761173e2-bab1-4f58-a909-071880733eb3)

**Comment by nihal467** [comment]
# Workflow 5

![Image](https://github.com/user-attachments/assets/703d94e9-0af0-4c52-b727-532d76e2201a)

**Comment by nihal467** [comment]
# Workflow 6

![Image](https://github.com/user-attachments/assets/9f8bdc26-e504-434f-86e4-158813f2642f)

**Comment by nihal467** [comment]
# Workflow 7

![Image](https://github.com/user-attachments/assets/991e0cbd-faed-45fe-a34b-c24437f9846f)

**Comment by nihal467** [comment]
# Workflow 8

![Image](https://github.com/user-attachments/assets/89f3be1f-febe-49b4-a5e6-3a1f2c4d32a8)

**Comment by nihal467** [comment]
# Workflow 9

![Image](https://github.com/user-attachments/assets/2555dbf7-f0b5-40b4-aa9a-3e1ab3a22415)

**Comment by rajku-dev** [comment]
I would like to work on some of the issues mentioned here. @nihal467

**Comment by rajku-dev** [comment]
> Hey [@nihal467](https://github.com/nihal467), I’d like to pick up some issues from here. I’ve successfully branched out this branch locally.

hey @AdityaJ2305 , where did you find the code for this new branch?

**Comment by sanjayh-2022** [comment]
@bodhish , I would like to work on some of the issues in this . Can you please assign me some of the issues to me ?

**Comment by modamaan** [comment]
@nihal467 i would like to work on Workflow 3

**Comment by bodhish** [comment]
Resolved
